language: objective-c
osx_image: xcode10
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- bundle install
script:
- .travis/build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false